# List of HornetQ servers
servers:
  - host: "localhost"
    port: 3333
    username: ""
    password: ""
    displayName: "localhost"

# hornetq mbeans. Exclude patterns with regex can be used to exclude any unwanted metrics.
mbeans:
  - domainName: "org.hornetq"
    excludePatterns: [
     "Acceptor|.*",
     "Address|.*",
     "ConnectionFactory|.*",
     "Server|.*",
     "Topic|.*"
    ]

# number of concurrent tasks
numberOfThreads: 10

#timeout for the thread
threadTimeout: 30

#prefix used to show up metrics in AppDynamics
metricPathPrefix:  "Custom Metrics|HornetQ|"

#Metric Overrides. Change this if you want to transform the metric key or value or its properties.
#metricOverrides:
